cars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name="detail"),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cars/<int:car_id>/add_color/', views.AddColorToCar.as_view(), name='add_color'),
    path('cars/<int:car_id>/assoc_color/<int:color_id>/', views.assoc_color, name='assoc_color'),
    path('cars/<int:car_id>/unassoc_color/<int:color_id>/', views.unassoc_color, name='unassoc_color'),
    path('colors/', views.ColorList.as_view(), name='colors_index'),
    path('colors/<int:pk>/update/', views.ColorCreate.as_view(), name='colors_update'),
    path('colors/<int:pk>/', views.ColorDetail.as_view(), name='color_detail'),
    path('colors/create/', views.ColorCreate.as_view(), name='colors_create'),
    path('colors/<int:pk>/update/', views.ColorUpdate.as_view(), name='colors_update'),
    path('colors/<int:pk>/delete/', views.ColorDelete.as_view(), name='colors_delete')
]

main_app/models.py
from django.db import models
from django.urls import reverse


HEADQUARTERS = (
    ('AF', 'Africa'),
    ('AN', 'Antarctica'),
    ('AS', 'Asia'),
    ('EU', 'Europe'),
    ('NA', 'North America'),
    ('OC', 'Oceania'),
    ('SA', 'South America'),
    ('CA', 'Central America'),
)

class Color(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('colors_detail', kwargs={'pk': self.id })

class Make(models.Model):
    manufacturer = models.CharField(max_length=100)
    head = models.CharField(
        max_length=100,
        choices=HEADQUARTERS,
        default=HEADQUARTERS[0][0],
    )

    def __str__(self):
        return self.manufacturer

class Car(models.Model):
    class Type(models.TextChoices):
        SEDAN = 'Sedan', 'Sedan'
        COUPE = 'Coupe', 'Coupe'
        SPORTS_CAR = 'Sports Car', 'Sports Car'
        WAGON = 'Wagon', 'Wagon'
        HATCHBACK = 'Hatchback', 'Hatchback'
        CONVERTIBLE = 'Convertible', 'Convertible'
        SUV = 'SUV', 'Sport Utility Vehicle'
        MINIVAN = 'Minivan', 'Minivan'
        PICKUP_TRUCK = 'Pickup Truck', 'Pickup Truck'

    make = models.ForeignKey(Make, on_delete=models.CASCADE, default=1)

    type = models.CharField(
        max_length=20,
        choices=Type.choices,
        default=Type.SEDAN
    )
    model = models.CharField(max_length=100)
    description = models.TextField(max_length=450)
    value = models.IntegerField()
    manufacture_date = models.DateField(default='1970-01-01')
    predecessor = models.CharField(max_length=100, default='')
    successor = models.CharField(max_length=100, default='')
    engine = models.CharField(default=None, null=True)  # Change default value to None
    image_url = models.URLField(
        default="https://www.vistacars.in/assets/product_images/default.png"
    )
    colors = models.ManyToManyField(Color)

    def available_colors(self):
        return self.colors.all()

    def __str__(self):
        return f"{self.make} - {self.model} ({self.id})"
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})

main_app/forms.py
from django import forms
from .models import Car, Color

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'


class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ['name', 'color']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import ListView, DetailView, DeleteView
from .models import Car, Color
from .forms import CarForm, ColorForm



# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cars_index(request):
    cars = Car.objects.all() 
    return render(request, 'cars/index.html', {'cars': cars})

def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    return render(request, 'cars/details.html', { 'car':car })

class CarCreate(CreateView):
    model = Car
    fields = ['make', 'type', 'model', 'description', 'value', 'manufacture_date', 'predecessor', 'successor', 'engine', 'image_url']

class CarUpdate(UpdateView):
    model = Car
    fields =[ 'type', 'make', 'description', 'value', 'manufacture_date', 'predecessor', 'successor', 'engine', 'image_url' ]

class CarDelete(DeleteView):
    model = Car
    success_url = '/cars'


class AddColorToCar(FormView):
    template_name = 'cars/add_color.html'
    form_class = ColorForm

    def form_valid(self, form):
        car_id = self.kwargs['car_id']
        car = Car.objects.get(id=car_id)
        color = form.save(commit=False)
        color.save()
        car.colors.add(color)
        return redirect('detail', car_id=car_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car_id = self.kwargs['car_id']
        car = Car.objects.get(id=car_id)
        context['car'] = car
        return context

def assoc_color(request, car_id, color_id):
    Car.objects.get(id=car_id).toys.add(color_id)
    return redirect('detail', car_id=car_id)

def unassoc_color(request, car_id, color_id):
    Car.objects.get(id=car_id).colors.remove(color_id)
    return redirect('detail', car_id=car_id)

class ColorList(ListView):
    model = Color

class ColorDetail(DetailView):
    model = Color

class ColorCreate(CreateView):
    model = Color

class ColorUpdate(UpdateView):
    model = Color
    fields = ['name', 'color']


class ColorDelete(DeleteView):
    model = Color
    success_url = '/colors'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Car Collector</h1>
<hr />
<p>Contact the Car Collector</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Car Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;Car Collector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url  'cars_create'%}">Add a Car</a></li>
            <li><a href="{% url 'index' %}">View All My Cars</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2024 Car Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/cars/details.html
{% extends 'base.html' %} {% block content %}

<h1>{{car.make}} Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.manufacturer }}</span>
        <p>Make: {{ car.make }}</p>
        <p>Description: {{ car.description|linebreaks }}</p>
        {% if car.value > 0 %}
        <p>Value: {{ car.value }}</p>
        {% else %}
        <p>Value: Unknown</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id %}">Edit</a>
        <a href="{% url 'cars_delete' car.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <table class="striped">
      <thead>
        <tr>
          <th>Manufacturer</th>
          <th>Headquarters</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ car.make.manufacturer }}</td>
          <td>{{ car.make.get_head_display }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <!-- This is all new markup to be added just above the <script> tag -->
    <hr />
    <div class="row">
      <div class="col s6">
        <h3>{{ car.make }}'s Colors</h3>
        {% if car.colors.count %} {% for color in car.colors.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: {% url 'unassoc_color' car.id color.id %}"
                >{{ color.name }}</span
              >
            </span>
          </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Available Colors</h5>
        {% endif %}
      </div>
      <!-- Available toys will come after this line -->
      <div class="col s6">
        <h3>Available Colors</h3>
        {% if colors.count %} {% for color in colors.all %}
        <div class="card">
          <div class="card-content">
            <div class="card-title">
              A <span style="color: {{ car.color }}">{{ car.color }}</span> {{
              color.name }}
            </div>
          </div>
          <div class="card-action">
            <form
              action="{% url 'assoc_color' car.id color.id %}"
              method="POST"
            >
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Available Colors</h5>
        {% endif %}
      </div>
    </div>
    <!-- New Markup Above -->
  </div>
</div>
{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %} {% block content %}

<h1>Car List</h1>
{% for car in cars %}
<div class="card">
  <a href="{% url 'detail' car.id %}">
  <div class="card-content">
    <div class="card-title">{{ car.make }}</div>
    <p>Make: {{ car.model }}</p>
    <p>Description: {{ car.description }}</p>
    {% if car.value > 0 %}
    <p>Value: ${{ car.value }}</p>
    {% else %}
    <p>Value: Unknown</p>
    {% endif %}
  </div>

{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Car</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.make }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' car.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %} {% block content %}
<h1>Add Car</h1>
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td>{{ form.type.label_tag }}</td>
      <td>{{ form.type }}</td>
    </tr>
  </table>
  <input type="submit" value="Submit" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/color_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Color</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'colors_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/color_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Colors</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Available Colors</span>
        <p>Color: {{ car.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'colors_update' color.id %}">Edit</a>
        <a href="{% url 'colros_delete' color.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/color_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Color</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/color_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Color List</h1>

{% for color in color_list %}
  <a href="{% url 'colors_detail' color.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ color.name }}</span>
            <p>Color: {{ color.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}